vmlinux.h: 只有在bpftool可用时才输出到文件
避免有人先编译(没有bpftool生成一个空的vmlinux.h),后安装bpftool.
此时vmlinux.h不会再更新出现找不到任何内核符号:

In file included from tutuicmptunnel.bpf.c:6:
../common/defs.h:38:19: error: field has incomplete type 'struct in6_addr'
38 | struct in6_addr address attribute((aligned(16))); // 客户端地址
| ^
../common/defs.h:38:10: note: forward declaration of 'struct in6_addr'
38 | struct in6_addr address attribute((aligned(16))); // 客户端地址
| ^
../common/defs.h:39:3: error: unknown type name '__be16'
39 | __be16 sport; // 客户端源端口
| ^
../common/defs.h:40:3: error: unknown type name '__be16'
40 | __be16 dport; // 客户端目的端口
| ^
../common/defs.h:44:3: error: unknown type name '__u64'
44 | __u64 age;
| ^
../common/defs.h:45:3: error: unknown type name '__u8'
45 | __u8 uid;
| ^
../common/defs.h:50:19: error: field has incomplete type 'struct in6_addr'

Signed-off-by: hrimfaxi <outmatch@gmail.com>

diff --git a/bpf/Makefile b/bpf/Makefile
--- a/bpf/Makefile
+++ b/bpf/Makefile
@@ -76,8 +76,13 @@ tutuicmptunnel.debug.skel.h: tutuicmptunnel.debug.bpf.o
 # Generate vmlinux.h (only if BTF is enabled)
 ifeq ($(USE_BTF),1)
 vmlinux.h:
-	@echo "Generating vmlinux.h..."
-	$(Q)$(BPFTOOL) btf dump file /sys/kernel/btf/vmlinux format c > $@
+	@if command -v $(BPFTOOL) >/dev/null 2>&1 ; then \
+	  echo "Generating vmlinux.h..."; \
+	  $(BPFTOOL) btf dump file /sys/kernel/btf/vmlinux format c > $@; \
+	else \
+	  echo "Error: $(BPFTOOL) not found or not executable"; \
+	  exit 1; \
+	fi;
 endif
 
 # Update dependencies
